---
title: "07 - metacommunity"
author: "Cole LaCroix"
date: "2025-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# set CRAN mirror (important when knitting)
options(repos = c(CRAN = "https://cloud.r-project.org"))

# install packages if not already installed
if(!require(here)) install.packages("here")
if(!require(terra)) install.packages("terra")
if(!require(randomForest)) install.packages("randomForest")
#Java Downloads from https://www.oracle.com/java/technologies/downloads/#jdk25-windows
#choose installer
if(!require(rJava)) install.packages("rJava")
if(!require(dismo)) install.packages("dismo")
if(!require(mgcv)) install.packages("mgcv")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(viridis)) install.packages("viridis")
if(!require(fields)) install.packages("fields")
```


```{r}
# load required packages
library(here)
library(terra)
library(randomForest)
library(rJava)
library(dismo)
library(mgcv)
library(ggplot2)
library(viridis)
library(fields)
```










